// Lista de presentes — gerada a partir do CHA.txt
const CATEGORIES = [
  "Eletroportáteis",
  "Utensílios de cozinha",
  "Louças e mesa posta",
  "Organização da cozinha",
  "Casa e lavanderia",
  "Panelas",
  "Itens grandes"
];

const ITEMS = [
  { id: "aspirador-de-po", name: "Aspirador de pó", category: "Eletroportáteis", links: [{ label: "Ver produto", url: "https://meli.la/1PSE1aB" }] },
  { id: "torradeira", name: "Torradeira", category: "Eletroportáteis", links: [{ label: "Ver produto", url: "https://meli.la/28GQC9a" }] },
  { id: "mixer", name: "Mixer", category: "Eletroportáteis", links: [{ label: "Ver produto", url: "https://meli.la/1gT47ai" }] },
  { id: "ferro-de-passar", name: "Ferro de passar", category: "Eletroportáteis", links: [{ label: "Ver produto", url: "https://meli.la/3178qji" }] },
  { id: "chaleira-eletrica", name: "Chaleira elétrica", category: "Eletroportáteis", links: [{ label: "Ver produto", url: "https://meli.la/1ZPPKaC" }] },
  { id: "multiprocessador", name: "Multiprocessador", category: "Eletroportáteis", links: [{ label: "Ver produto", url: "https://meli.la/2dHVhCE" }] },
  { id: "sanduicheira", name: "Sanduicheira", category: "Eletroportáteis", links: [{ label: "Opção 1", url: "https://meli.la/2mGegqC" }, { label: "Opção 2", url: "https://meli.la/2kz3ZpU" }] },
  { id: "cafeteira", name: "Cafeteira", category: "Eletroportáteis", links: [{ label: "Ver produto", url: "https://meli.la/1L1bCyw" }] },
  { id: "batedeira", name: "Batedeira", category: "Eletroportáteis", links: [{ label: "Ver produto", url: "https://meli.la/1psXpEz" }] },

  { id: "espatulas-de-silicone", name: "Espátulas de silicone", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1Mx8mQV" }] },
  { id: "rolo-de-massa", name: "Rolo de massa", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/2ywDg8T" }] },
  { id: "saleiro", name: "Saleiro", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/16uLh9B" }] },
  { id: "porta-utensilios", name: "Porta utensílios", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1NP1Yea" }] },
  { id: "tabua-grande-de-carne", name: "Tábua grande de carne", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1Y95ipx" }] },
  { id: "escorredor-de-macarrao", name: "Escorredor de macarrão", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/2hpmHSQ" }] },
  { id: "abridor-de-latas", name: "Abridor de latas", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1Joqms4" }] },
  { id: "porta-temperos", name: "Porta temperos", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/2dJhQNn" }] },
  { id: "ralador-inox", name: "Ralador inox", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1f4dShW" }] },
  { id: "peneiras", name: "Peneiras", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1uqdTQU" }] },
  { id: "medidor", name: "Medidor", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://s.shopee.com.br/W6fosNdQP" }] },
  { id: "cortador-de-pizza", name: "Cortador de pizza", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1LuRvka" }] },
  { id: "faca-de-bolo-e-espatula", name: "Faca de bolo e espátula", category: "Utensílios de cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1z9PEGf" }] },

  { id: "taca-de-agua", name: "Taça de água", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/2CkJic1" }] },
  { id: "bows-mesa", name: "Bows mesa", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/2CkJic1" }] },
  { id: "prato-de-sobremesa", name: "Prato de sobremesa", category: "Louças e mesa posta", links: [{ label: "Opção 1", url: "https://meli.la/1pjcsqW" }, { label: "Opção 2", url: "https://meli.la/19msw22" }] },
  { id: "prato-fundo", name: "Prato fundo", category: "Louças e mesa posta", links: [{ label: "Opção 1", url: "https://meli.la/1pjcsqW" }, { label: "Opção 2", url: "https://meli.la/2TtqMGa" }] },
  { id: "prato-raso", name: "Prato raso", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/1fiVEaC" }] },
  { id: "bows-japones", name: "Bows japonês", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/29S5bPb" }] },
  { id: "xicaras-de-cha", name: "Xícaras de chá", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/1CnAt4N" }] },
  { id: "jarra-de-suco", name: "Jarra de suco", category: "Louças e mesa posta", links: [{ label: "Opção 1", url: "https://meli.la/277n8PA" }, { label: "Opção 2", url: "https://s.shopee.com.br/BTpObiVnH" }] },
  { id: "jogo-de-mantimentos", name: "Jogo de mantimentos", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/183Ffjo" }] },
  { id: "manteigueira", name: "Manteigueira", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/2ksr3Ag" }] },
  { id: "talheres-de-servir", name: "Talheres de servir", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://s.shopee.com.br/2LYJuaZ6y4" }] },
  { id: "aparelho-de-jantar", name: "Aparelho de jantar", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/2Qky2eS" }] },
  { id: "jogo-japones", name: "Jogo japonês", category: "Louças e mesa posta", links: [{ label: "Ver produto", url: "https://meli.la/2PLLJgz" }] },
  { id: "tacas-de-sobremesa", name: "Taças de sobremesa", category: "Louças e mesa posta", links: [{ label: "Opção 1", url: "https://meli.la/2SacHbW" }, { label: "Opção 2", url: "https://meli.la/1Xt3vYo" }] },

  { id: "potes-de-marmita", name: "Potes de marmita", category: "Organização da cozinha", links: [{ label: "Ver produto", url: "https://meli.la/277n8PA" }] },
  { id: "cestos-organizadores-de-geladeira", name: "Cestos organizadores de geladeira", category: "Organização da cozinha", links: [{ label: "Opção 1", url: "https://meli.la/2DXjTNF" }, { label: "Opção 2", url: "https://meli.la/32mHJfs" }] },
  { id: "porta-bolo", name: "Porta bolo", category: "Organização da cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1QeYRN4" }] },
  { id: "frios", name: "Frios", category: "Organização da cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1c6tAyz" }] },
  { id: "forma-de-pizza", name: "Forma de pizza", category: "Organização da cozinha", links: [{ label: "Ver produto", url: "https://meli.la/1FpJeHq" }] },
  { id: "porta-papel-toalha", name: "Porta papel toalha", category: "Organização da cozinha", links: [{ label: "Ver produto", url: "https://meli.la/2XoNgSA" }] },
  { id: "formas-de-bolo", name: "Formas de bolo", category: "Organização da cozinha", links: [{ label: "Ver produto", url: "https://meli.la/2bJh8U2" }] },
  { id: "formas-de-assado", name: "Formas de assado", category: "Organização da cozinha", links: [{ label: "Opção 1", url: "https://meli.la/32SddPU" }, { label: "Opção 2", url: "https://meli.la/1q3cAqv" }] },

  { id: "organizador-de-lavanderia", name: "Organizador de lavanderia", category: "Casa e lavanderia", links: [{ label: "Ver produto", url: "https://meli.la/18rt3Yv" }] },
  { id: "balde", name: "Balde", category: "Casa e lavanderia", links: [{ label: "Ver produto", url: "https://meli.la/24g5etf" }] },
  { id: "cesto-de-limpeza", name: "Cesto de limpeza", category: "Casa e lavanderia", links: [{ label: "Ver produto", url: "https://meli.la/2xWNttx" }] },
  { id: "cesto-de-lixo", name: "Cesto de lixo", category: "Casa e lavanderia", links: [{ label: "Ver produto", url: "https://meli.la/2tyvbWh" }] },
  { id: "cesto-de-roupa-suja", name: "Cesto de roupa suja", category: "Casa e lavanderia", links: [{ label: "Ver produto", url: "https://meli.la/1BSbswb" }] },
  { id: "cabides", name: "Cabides", category: "Casa e lavanderia", links: [{ label: "Ver produto", url: "https://meli.la/1o6Qd5n" }] },
  { id: "arara-para-roupas", name: "Arara para roupas", category: "Casa e lavanderia", links: [{ label: "Ver produto", url: "https://meli.la/2iUChMF" }] },
  { id: "tapete-de-porta", name: "Tapete de porta", category: "Casa e lavanderia", links: [{ label: "Ver produto", url: "https://meli.la/31NxquL" }] },

  { id: "jogo-de-panelas", name: "Jogo de panelas", category: "Panelas", links: [{ label: "Opção 1", url: "https://meli.la/2LCpWFQ" }, { label: "Opção 2", url: "https://meli.la/32nfYJd" }] },

  { id: "sofa", name: "Sofá", category: "Itens grandes", links: [] },
  { id: "mesa-com-cadeiras", name: "Mesa com cadeiras", category: "Itens grandes", links: [] },
  { id: "televisao", name: "Televisão", category: "Itens grandes", links: [] },
  { id: "maquina-de-lavar-loucas", name: "Máquina de lavar louça", category: "Itens grandes", links: [] },
];
