// Lista de presentes — gerada a partir do CHA.txt
// Preço e foto são atualizados por scripts/atualiza-catalogo.mjs.
const CATEGORIES = [
  "Eletroportáteis",
  "Utensílios de cozinha",
  "Louças e mesa posta",
  "Organização da cozinha",
  "Casa e lavanderia",
  "Cama e banho",
  "Panelas",
  "Itens grandes"
];

const ITEMS = [
  { id: "aspirador-de-po", name: "Aspirador de pó", category: "Eletroportáteis", image: "assets/products/aspirador-de-po.webp", price: 466.44, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1PSE1aB" }] },
  { id: "torradeira", name: "Torradeira", category: "Eletroportáteis", image: "assets/products/torradeira.webp", price: 124.45, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/28GQC9a" }] },
  { id: "mixer", name: "Mixer", category: "Eletroportáteis", image: "assets/products/mixer.webp", price: 164.35, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1gT47ai" }] },
  { id: "ferro-de-passar", name: "Ferro de passar", category: "Eletroportáteis", image: "assets/products/ferro-de-passar.jpg", price: 90.95, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://www.amazon.com.br/Ferro-Passar-Antiaderente-Oster-GCSTBS5002/dp/B09LNKQYND" }] },
  { id: "chaleira-eletrica", name: "Chaleira elétrica", category: "Eletroportáteis", image: "assets/products/chaleira-eletrica.webp", price: 67.73, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1ZPPKaC" }] },
  { id: "multiprocessador", name: "Multiprocessador", category: "Eletroportáteis", image: "assets/products/multiprocessador.webp", price: 186.10, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2dHVhCE" }] },
  { id: "sanduicheira", name: "Sanduicheira", category: "Eletroportáteis", image: "assets/products/sanduicheira.webp", price: 89.91, precoEm: "2026-09-17", links: [{ label: "Opção 1", url: "https://meli.la/2mGegqC" }, { label: "Opção 2", url: "https://meli.la/2kz3ZpU" }] },
  { id: "cafeteira", name: "Cafeteira", category: "Eletroportáteis", image: "assets/products/cafeteira.webp", price: 113.25, precoEm: "2026-09-17", links: [{ label: "Opção 1", url: "https://meli.la/1L1bCyw" }, { label: "Opção 2", url: "https://meli.la/2H6WoWM" }] },
  { id: "batedeira", name: "Batedeira", category: "Eletroportáteis", image: "assets/products/batedeira.webp", price: 171.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1psXpEz" }] },

  { id: "espatulas-de-silicone", name: "Espátulas de silicone", category: "Utensílios de cozinha", image: "assets/products/espatulas-de-silicone.webp", price: 55.10, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1Mx8mQV" }] },
  { id: "rolo-de-massa", name: "Rolo de massa", category: "Utensílios de cozinha", image: "assets/products/rolo-de-massa.webp", price: 149.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2ywDg8T" }] },
  { id: "saleiro", name: "Saleiro", category: "Utensílios de cozinha", image: "assets/products/saleiro.webp", price: 78.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/16uLh9B" }] },
  { id: "porta-utensilios", name: "Porta utensílios", category: "Utensílios de cozinha", image: "assets/products/porta-utensilios.webp", price: 40.75, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1NP1Yea" }] },
  { id: "tabua-grande-de-carne", name: "Tábua grande de carne", category: "Utensílios de cozinha", image: "assets/products/tabua-grande-de-carne.webp", price: 55.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1Y95ipx" }] },
  { id: "escorredor-de-macarrao", name: "Escorredor de macarrão", category: "Utensílios de cozinha", image: "assets/products/escorredor-de-macarrao.webp", price: 29.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2hpmHSQ" }] },
  { id: "abridor-de-latas", name: "Abridor de latas", category: "Utensílios de cozinha", image: "assets/products/abridor-de-latas.webp", price: 32.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1Joqms4" }] },
  { id: "porta-temperos", name: "Porta temperos", category: "Utensílios de cozinha", image: "assets/products/porta-temperos.jpg", price: 51.90, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://www.amazon.com.br/Porta-Temperos-Giratório-Organizador-Cozinha/dp/B0H95JQNWN" }] },
  { id: "ralador-inox", name: "Ralador inox", category: "Utensílios de cozinha", image: "assets/products/ralador-inox.webp", price: 19.90, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1f4dShW" }] },
  { id: "peneiras", name: "Peneiras", category: "Utensílios de cozinha", image: "assets/products/peneiras.webp", price: 19.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1uqdTQU" }] },
  { id: "medidor", name: "Medidor", category: "Utensílios de cozinha", image: "assets/products/medidor.webp", links: [{ label: "Ver produto", url: "https://s.shopee.com.br/W6fosNdQP" }] },
  { id: "cortador-de-pizza", name: "Cortador de pizza", category: "Utensílios de cozinha", image: "assets/products/cortador-de-pizza.webp", price: 280.24, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1LuRvka" }] },
  { id: "faca-de-bolo-e-espatula", name: "Faca de bolo e espátula", category: "Utensílios de cozinha", image: "assets/products/faca-de-bolo-e-espatula.webp", price: 24.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1z9PEGf" }] },
  { id: "pano-de-prato", name: "Pano de prato", category: "Utensílios de cozinha", image: "assets/products/pano-de-prato.jpg", links: [{ label: "Ver produto", url: "https://s.shopee.com.br/AAHF93i18f" }] },

  { id: "taca-de-agua", name: "Taça de água", category: "Louças e mesa posta", image: "assets/products/taca-de-agua.webp", price: 74.09, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2CkJic1" }] },
  { id: "bows-mesa", name: "Bows mesa", category: "Louças e mesa posta", image: "assets/products/bows-mesa.jpg", price: 121.83, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://www.amazon.com.br/Tigelas-TRAMONTINA-Floralis-Porcelana-Decorada/dp/B0H34VZHBV" }] },
  { id: "prato-de-sobremesa", name: "Prato de sobremesa", category: "Louças e mesa posta", image: "assets/products/prato-de-sobremesa.webp", price: 149.13, precoEm: "2026-09-17", links: [{ label: "Opção 1", url: "https://meli.la/1pjcsqW" }, { label: "Opção 2", url: "https://meli.la/19msw22" }] },
  { id: "prato-fundo", name: "Prato fundo", category: "Louças e mesa posta", image: "assets/products/prato-fundo.webp", price: 149.13, precoEm: "2026-09-17", links: [{ label: "Opção 1", url: "https://meli.la/1pjcsqW" }, { label: "Opção 2", url: "https://meli.la/2TtqMGa" }] },
  { id: "prato-raso", name: "Prato raso", category: "Louças e mesa posta", image: "assets/products/prato-raso.webp", price: 232.07, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1fiVEaC" }] },
  { id: "bows-japones", name: "Bows japonês", category: "Louças e mesa posta", image: "assets/products/bows-japones.webp", price: 117.39, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/29S5bPb" }] },
  { id: "xicaras-de-cha", name: "Xícaras de chá", category: "Louças e mesa posta", image: "assets/products/xicaras-de-cha.webp", price: 130.79, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1CnAt4N" }] },
  { id: "jarra-de-suco", name: "Jarra de suco", category: "Louças e mesa posta", image: "assets/products/jarra-de-suco.jpg", links: [{ label: "Ver produto", url: "https://s.shopee.com.br/1gIbmLDZ6Y" }] },
  { id: "jogo-de-mantimentos", name: "Jogo de mantimentos", category: "Louças e mesa posta", image: "assets/products/jogo-de-mantimentos.webp", price: 93.91, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/183Ffjo" }] },
  { id: "manteigueira", name: "Manteigueira", category: "Louças e mesa posta", image: "assets/products/manteigueira.webp", price: 59.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2ksr3Ag" }] },
  { id: "talheres-de-servir", name: "Talheres de servir", category: "Louças e mesa posta", image: "assets/products/talheres-de-servir.jpg", price: 83.51, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://www.amazon.com.br/Conjunto-Talheres-Servir-Inox-Firenze/dp/B0CV63P5LY" }] },
  { id: "aparelho-de-jantar", name: "Aparelho de jantar", category: "Louças e mesa posta", image: "assets/products/aparelho-de-jantar.webp", price: 229.45, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2Qky2eS" }] },
  { id: "jogo-japones", name: "Jogo japonês", category: "Louças e mesa posta", image: "assets/products/jogo-japones.webp", price: 132.95, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2PLLJgz" }] },
  { id: "tacas-de-sobremesa", name: "Taças de sobremesa", category: "Louças e mesa posta", image: "assets/products/tacas-de-sobremesa.webp", price: 310.91, precoEm: "2026-09-17", links: [{ label: "Opção 1", url: "https://meli.la/2SacHbW" }, { label: "Opção 2", url: "https://meli.la/1Xt3vYo" }] },

  { id: "potes-de-marmita", name: "Potes de marmita", category: "Organização da cozinha", image: "assets/products/potes-de-marmita.webp", price: 62.60, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/277n8PA" }] },
  { id: "cestos-organizadores-de-geladeira", name: "Cestos organizadores de geladeira", category: "Organização da cozinha", image: "assets/products/cestos-organizadores-de-geladeira.webp", price: 90.12, precoEm: "2026-09-17", links: [{ label: "Opção 1", url: "https://meli.la/2DXjTNF" }, { label: "Opção 2", url: "https://meli.la/32mHJfs" }] },
  { id: "porta-bolo", name: "Porta bolo", category: "Organização da cozinha", image: "assets/products/porta-bolo.webp", price: 135.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1QeYRN4" }] },
  { id: "frios", name: "Frios", category: "Organização da cozinha", image: "assets/products/frios.webp", price: 52.52, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1c6tAyz" }] },
  { id: "forma-de-pizza", name: "Forma de pizza", category: "Organização da cozinha", image: "assets/products/forma-de-pizza.webp", price: 151.47, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1FpJeHq" }] },
  { id: "porta-papel-toalha", name: "Porta papel toalha", category: "Organização da cozinha", image: "assets/products/porta-papel-toalha.webp", price: 77.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2XoNgSA" }] },
  { id: "formas-de-bolo", name: "Formas de bolo", category: "Organização da cozinha", image: "assets/products/formas-de-bolo.webp", price: 57.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2bJh8U2" }] },
  { id: "formas-de-assado", name: "Formas de assado", category: "Organização da cozinha", image: "assets/products/formas-de-assado.webp", price: 56.17, precoEm: "2026-09-17", links: [{ label: "Opção 1", url: "https://meli.la/32SddPU" }, { label: "Opção 2", url: "https://meli.la/1q3cAqv" }] },
  { id: "assadeiras", name: "Assadeiras", category: "Organização da cozinha", image: "assets/products/assadeiras.webp", price: 128.15, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/17gjWz1" }] },

  { id: "organizador-de-lavanderia", name: "Organizador de lavanderia", category: "Casa e lavanderia", image: "assets/products/organizador-de-lavanderia.webp", price: 73.49, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/18rt3Yv" }] },
  { id: "balde", name: "Balde", category: "Casa e lavanderia", image: "assets/products/balde.webp", price: 74.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/24g5etf" }] },
  { id: "cesto-de-limpeza", name: "Cesto de limpeza", category: "Casa e lavanderia", image: "assets/products/cesto-de-limpeza.webp", price: 50.18, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2xWNttx" }] },
  { id: "cesto-de-roupa-suja", name: "Cesto de roupa suja", category: "Casa e lavanderia", image: "assets/products/cesto-de-roupa-suja.webp", price: 119.00, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1BSbswb" }] },
  { id: "cabides", name: "Cabides", category: "Casa e lavanderia", image: "assets/products/cabides.webp", price: 66.40, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1o6Qd5n" }] },
  { id: "arara-para-roupas", name: "Arara para roupas", category: "Casa e lavanderia", image: "assets/products/arara-para-roupas.webp", price: 89.16, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/2iUChMF" }] },
  { id: "tapete-de-porta", name: "Tapete de porta", category: "Casa e lavanderia", image: "assets/products/tapete-de-porta.webp", price: 50.94, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/31NxquL" }] },
  { id: "tabua-de-passar-roupa", name: "Tábua de passar roupa", category: "Casa e lavanderia", image: "assets/products/tabua-de-passar-roupa.webp", price: 189.90, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/1N4jyLn" }] },
  { id: "mop", name: "Mop", category: "Casa e lavanderia", image: "assets/products/mop.webp", price: 101.36, precoEm: "2026-09-17", links: [{ label: "Ver produto", url: "https://meli.la/23azDKb" }] },
  { id: "lixeiras", name: "Lixeiras", category: "Casa e lavanderia", image: "assets/products/lixeiras.jpg", links: [{ label: "Ver produto", url: "https://s.shopee.com.br/9V1YPJYARH" }] },

  { id: "jogo-de-toalhas", name: "Jogo de toalhas", category: "Cama e banho", price: 154.63, precoEm: "2026-09-18", links: [{ label: "Ver produto", url: "https://www.mercadolivre.com.br/jogo-toalha-banho-e-rosto-4pcs-100-algodao-520g-atlantica/up/MLBU4593843372?pdp_filters=item_id%3AMLB7330517578" }] },
  { id: "jogo-de-lencol-king", name: "Jogo de lençol king", category: "Cama e banho", price: 159.99, precoEm: "2026-09-18", links: [{ label: "Ver produto", url: "https://www.mercadolivre.com.br/jogo-lencol-king-4-pecas-600-fios-verde-oliva-moderno-luxo/up/MLBU3933575290?pdp_filters=item_id%3AMLB4639854293" }] },

  { id: "jogo-de-panelas", name: "Jogo de panelas", category: "Panelas", image: "assets/products/jogo-de-panelas.webp", price: 388.30, precoEm: "2026-09-17", links: [{ label: "Opção 1", url: "https://meli.la/2LCpWFQ" }, { label: "Opção 2", url: "https://meli.la/32nfYJd" }] },

  { id: "sofa", name: "Sofá", category: "Itens grandes", image: "assets/products/sofa.svg", links: [] },
  { id: "mesa-com-cadeiras", name: "Mesa com cadeiras", category: "Itens grandes", image: "assets/products/mesa-com-cadeiras.svg", links: [] },
  { id: "televisao", name: "Televisão", category: "Itens grandes", image: "assets/products/televisao.svg", links: [] },
  { id: "maquina-de-lavar-loucas", name: "Máquina de lavar louça", category: "Itens grandes", image: "assets/products/maquina-de-lavar-loucas.svg", links: [] },
];
